name: ğŸ—ï¸ ê°œë°œ 
run-name: "Name: ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on: 
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'ë°°í¬í•  dev-qa- ì„œë²„ì˜ ë’·ë¶€ë¶„ ì´ë¦„ì„ ì…ë ¥í•´ì£¼ì„¸ìš”. ex)dev-qa-lenditapp ì‹œ lenditappë§Œ ì…ë ¥'
        type: string

jobs:
  validation:
    name: validation
    uses: nasir17git/called/.github/workflows/env.yaml@main
    with:
      env_name: prod
      
    
  calling:
    needs: validation
    if: needs.validation.outputs.in_progress_check == '1' && needs.validation.outputs.branch_check == '1' && always()
    name: build
    uses: nasir17git/called/.github/workflows/con-name.yaml@main
    secrets: inherit

