name: Caller Workflow
run-name: ì´ë¦„ -  ${{ github.ref_name }} > ${{inputs.CONFIRMATION }} by ${{ github.actor }}
on:
  push:
  workflow_dispatch:
    inputs:
      APP_NAME:
        type: string
      NEED_MYSQL:
        default: true
        type: boolean
      TARGET:
        description: 'ğŸš€ğŸš€ìš´ì˜ í™˜ê²½ğŸš€ğŸš€, ë°°í¬ ëŒ€ìƒì„ ì„ íƒí•´ì£¼ì„¸ìš”.'
        required: true
        type: choice
        options:
          - ""
          - lendit
          - service-dev

jobs:
   calling:
    name: build
    uses: nasir17git/called/.github/workflows/called.yaml@main
    with:
      APP_NAME: ${{ inputs.APP_NAME }}
      NEED_MYSQL: ${{ inputs.NEED_MYSQL }}
      TARGET: ${{ inputs.NEED_MYSQL }}
    secrets: inherit
