name: Caller Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      APP_NAME:
        type: string
      NEED_MYSQL:
        default: true
        type: boolean
      CONFIRMATION:
        description: ğŸš€ ğŸš€ ìš´ì˜ í™˜ê²½ì— ë°°í¬í•©ë‹ˆë‹¤.
        required: true
        type: boolean

jobs:
   calling:
    name: build
    uses: nasir17git/called/.github/workflows/called.yaml@main
    with:
      APP_NAME: ${{ inputs.APP_NAME }}
      NEED_MYSQL: ${{ inputs.NEED_MYSQL }}
    secrets: inherit
