name: ğŸ“ wdwdwdw
run-name: ğŸ“, ${{ github.event.head_commit.message }}

on: 
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:
    inputs:
      SKIP_TEST:
        # ë¹Œë“œ í…ŒìŠ¤íŠ¸ë¥¼ ìƒëµí•˜ë ¤ë©´ true
        type: boolean
      all:
        type: boolean
        description: check for all
      aaa:
        type: boolean
        description: check for aaa
      bbb:
        type: boolean
        description: check for bbb
      ccc:
        type: boolean
        description: check for ccc
      choice:
        type: choice
        description: "dddd"
        options:
          - ""
          - choice1
          - choice2
      string:
        type: string
        description: "ì²«ë²ˆì§¸ ì¤„ \n ë‘ë²ˆì§¸ ì¤„"

jobs:
  input_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Dump inputs
        env:
          INPUT_CONTEXT: ${{ toJson(inputs) }}
        run: |
          echo "$INPUT_CONTEXT"
  module_check:
    name: module_check
    uses: nasir17git/called/.github/workflows/multi-check.yaml@main
    with: # inputsë¥¼ í•œë²ˆì— ë„£ëŠ”ë°©ë²•ì´ ìˆìœ¼ë ¤ë‚˜ ë§¤ë²ˆ ì„¤ì •í•˜ëŠ”ê±´ ì¢€ê·¸ë ‡ê³  pass:${{inputs}}ê°™ì´ ë˜ì§€ë©´ ë‚˜ì¤‘ì— ${{inputs.pass.aaa}}ì‹ìœ¼ë¡œ ì“¸ìˆ˜ì—†ë‚˜
      SKIP_TEST: ${{inputs.SKIP_TEST}}
      all: ${{inputs.all}}
      aaa: ${{inputs.aaa}}
      bbb: ${{inputs.bbb}}
      ccc: ${{inputs.ccc}}
      pass: (${{inputs.choice}} || ${{inputs.string}})
      # pass: ${{inputs}}
    secrets: inherit
#   build:
#     name: build
#     uses: nasir17git/called/.github/workflows/multi-main.yaml@main
#     secrets: inherit